"""Shell completion, generated from the command table rather than maintained.

A hand-written completion script is a second copy of the command list, and a
second copy of a list is a list that is wrong. This one is generated from
`cli.COMMANDS` and from each module's own argparse parser at the moment it is
printed, so a command added today completes today and a flag renamed today
stops being suggested today.

Flags are discovered by importing the module and reading its parser, which is
the only source that cannot disagree with `--help`. That import costs a moment
at generation time and nothing at completion time: the output is a static
script the shell sources once.

Why the generated script is static rather than calling back into Python: a
completion that shells out to `python3 -c` on every Tab press adds ~80ms to
every keystroke sequence, which is the difference between completion that feels
free and completion people turn off.
"""

from __future__ import annotations

import argparse
import contextlib
import importlib
import io

from adder.cli import COMMANDS

SHELLS = ("bash", "zsh", "fish")

# Flags the dispatcher owns, which no module's parser knows about.
META = ("help", "version", "--help", "-h", "--version", "-V")


def flags_for(command: str) -> list[str]:
    """Every option string that command's parser accepts.

    Returns `[]` rather than raising when a module cannot be imported or does
    not build its parser in `main`: a completion script that fails to generate
    because one command is broken is worse than one missing a few flags.
    """
    cmd = next((c for c in COMMANDS if c.name == command), None)
    if cmd is None:
        return []
    try:
        mod = importlib.import_module(cmd.module)
    except Exception:
        return []

    captured: list[argparse.ArgumentParser] = []
    real_parse = argparse.ArgumentParser.parse_args

    def spy(self, args=None, namespace=None):
        captured.append(self)
        raise _StopError

    argparse.ArgumentParser.parse_args = spy       # type: ignore[method-assign]
    try:
        # Every module builds its parser inside `main`, so the parser only
        # exists during a call. Running it with `--help` would exit; running it
        # with no arguments would do the work. So `parse_args` is intercepted:
        # by the time it is reached the parser is fully built.
        with contextlib.suppress(_StopError, SystemExit, Exception), \
                contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            mod.main([])
    finally:
        argparse.ArgumentParser.parse_args = real_parse  # type: ignore[method-assign]

    out: list[str] = []
    for parser in captured:
        for action in parser._actions:
            out.extend(s for s in action.option_strings if s.startswith("--"))
    return sorted(set(out))


class _StopError(Exception):
    """Raised to unwind out of `main` once the parser has been built."""


def _table() -> list[tuple[str, list[str]]]:
    return [(c.name, flags_for(c.name)) for c in COMMANDS]


def bash() -> str:
    rows = _table()
    names = " ".join(n for n, _ in rows) + " " + " ".join(META)
    cases = "\n".join(
        f'    {name}) opts="{" ".join(flags)}" ;;' for name, flags in rows if flags)
    return f"""# adder completion for bash. Generated by `adder completion bash`.
# Install:  adder completion bash > /etc/bash_completion.d/adder
#      or:  eval "$(adder completion bash)"
_adder_complete() {{
  local cur prev opts
  COMPREPLY=()
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "{names}" -- "$cur") )
    return 0
  fi
  case "${{COMP_WORDS[1]}}" in
{cases}
    *) opts="" ;;
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
}}
complete -F _adder_complete adder
"""


def zsh() -> str:
    rows = _table()
    descriptions = "\n".join(
        f"    '{c.name}:{c.summary.replace(chr(39), '')}'" for c in COMMANDS)
    cases = "\n".join(
        f"      {name}) _values 'option' {' '.join(flags)} ;;"
        for name, flags in rows if flags)
    return f"""#compdef adder
# adder completion for zsh. Generated by `adder completion zsh`.
# Install:  adder completion zsh > "${{fpath[1]}}/_adder"
_adder() {{
  local -a commands
  commands=(
{descriptions}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  case "${{words[2]}}" in
{cases}
      *) _files ;;
  esac
}}
_adder "$@"
"""


def fish() -> str:
    rows = _table()
    lines = [
        "# adder completion for fish. Generated by `adder completion fish`.",
        "# Install:  adder completion fish > ~/.config/fish/completions/adder.fish",
        "complete -c adder -f",
    ]
    for c in COMMANDS:
        desc = c.summary.replace("'", "")
        lines.append(
            f"complete -c adder -n '__fish_use_subcommand' -a '{c.name}' -d '{desc}'")
    for name, flags in rows:
        for flag in flags:
            lines.append(
                f"complete -c adder -n '__fish_seen_subcommand_from {name}' "
                f"-l '{flag.lstrip('-')}'")
    return "\n".join(lines) + "\n"


def script(shell: str) -> str:
    if shell not in SHELLS:
        raise ValueError(f"unknown shell {shell!r}; known: {', '.join(SHELLS)}")
    return {"bash": bash, "zsh": zsh, "fish": fish}[shell]()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="adder completion",
        description="Print a shell completion script generated from the command table.")
    ap.add_argument("shell", nargs="?", choices=SHELLS,
                    help="which shell (default: guess from $SHELL)")
    a = ap.parse_args(argv)

    shell = a.shell
    if shell is None:
        import os

        name = os.path.basename(os.environ.get("SHELL", ""))
        shell = next((s for s in SHELLS if s == name), None)
        if shell is None:
            print("adder completion: name a shell — "
                  f"{', '.join(SHELLS)}", file=__import__("sys").stderr)
            return 2
    print(script(shell), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
